const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const root=path.resolve(__dirname,'../..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
let passed=0;async function test(n,f){await f();passed++;console.log('PASS '+n)}
function load(file,mocks={},globals={}){const m={exports:{}};const out=ts.transpileModule(read(file),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true},reportDiagnostics:true});assert.equal(out.diagnostics.filter(d=>d.category===ts.DiagnosticCategory.Error).length,0);vm.runInNewContext(out.outputText,{module:m,exports:m.exports,require:n=>{if(n in mocks)return mocks[n];if(n.startsWith('@/'))return load(n.slice(2)+'.ts',mocks,globals);return require(n)},Date,JSON,Set,Number,String,Error,AbortSignal,console,...globals});return m.exports}
const origin='https://app.jride.net',product='e27fbe12-903e-452e-96ec-04d34cbf1982',other='4cc34e1f-511d-431e-82e7-bd075e45c6a8',stamp='2026-09-23T05:16:53.008350+00:00';
const base={order_code:'AG-TEST',expected_updated_at:stamp,reason_code:'sold_outside_jride',affected_product_ids:[product],confirm_cancel_all:true,reason_note:''};
function harness(opt={}){const calls=[];const api=load('app/api/agrimarket/producer/orders/cancel-reservation/route.ts',{'../../../_lib/server':{agrimarketEnabled:()=>!opt.disabled,agrimarketDisabledResponse:()=>({status:503}),requireAgrimarketProducer:async()=>opt.denied?{ok:false,response:{status:401}}:{ok:true,producer:{id:'own-farm'}},createServiceSupabase:()=>({rpc:async(name,args)=>{calls.push({name,args});return opt.dbError?{error:{message:'SECRET'}}:{data:opt.result||{ok:true,status:'cancelled'}}}}),jsonNoStore:(status,body)=>({status,body})}});return {api,calls,req:(extra={},org=origin)=>({nextUrl:new URL(origin+'/api/agrimarket/producer/orders/cancel-reservation'),headers:new Headers({origin:org}),text:async()=>opt.raw??JSON.stringify({...base,...extra})})}}
function all(node,pred,out=[]){if(!node||typeof node!=='object')return out;if(pred(node))out.push(node);for(const n of [node.props?.children].flat(Infinity))all(n,pred,out);return out}
const flush=()=>new Promise(r=>setImmediate(r));
function ui(){let i=0,tree;const slots=[],calls=[],completed=[];let order={order_code:'AG-TEST',status:'awaiting_harvest',updated_at:stamp,items:[{product_id:product,product_name:'Pig - Belly',quantity:2,selling_unit:'kg'},{product_id:other,product_name:'Pig - Ribs',quantity:1,selling_unit:'kg'}]};const react={useRef(v){const j=i++;if(!(j in slots))slots[j]={current:v};return slots[j]},useState(v){const j=i++;if(!(j in slots))slots[j]=v;return [slots[j],n=>{slots[j]=typeof n==='function'?n(slots[j]):n}]}};const jsx=(type,props)=>({type,props});const C=load('app/agrimarket/producer/CancelReservation.tsx',{react,'react/jsx-runtime':{jsx,jsxs:jsx},'@/lib/agrimarket/farmerSessionClient':{farmerSessionHeaders:()=>({})}},{fetch:async(url,opt)=>{calls.push({url,opt});return {ok:true,json:async()=>({ok:true,message:'Cancelled entire reservation.'})}}}).default;function render(){i=0;tree=C({order,accountCode:'AGF-TEST',busy:false,onBusy:()=>{},onComplete:async m=>completed.push(m)});return tree}render();return {render,calls,completed,find:p=>all(tree,p)[0],findAll:p=>all(tree,p),change:()=>{order={...order,updated_at:'2026-09-23T05:17:00.000000+00:00'}},get tree(){return tree}}}
(async()=>{
 await test('authenticated cancellation binds producer identity and preserves microsecond revision',async()=>{const h=harness();const x=await h.api.POST(h.req({producer_id:'other'}));assert.equal(x.status,200);assert.equal(h.calls[0].args.p_producer_id,'own-farm');assert.equal(h.calls[0].args.p_expected_updated_at,stamp);assert.equal(h.calls[0].args.p_reason_code,'sold_outside_jride');});
 await test('no authentication, foreign origin and disabled service cannot mutate',async()=>{for(const options of [{denied:true},{disabled:true}]){const h=harness(options);assert((await h.api.POST(h.req())).status>=400);assert.equal(h.calls.length,0)}const h=harness();assert.equal((await h.api.POST(h.req({},'https://bad.test'))).status,403);assert.equal(h.calls.length,0);});
 await test('reason, unavailable cuts and explicit entire-order confirmation are mandatory',async()=>{for(const changes of [{reason_code:''},{reason_code:'customer_fault'},{affected_product_ids:[]},{affected_product_ids:[product,product]},{affected_product_ids:['bad']},{confirm_cancel_all:false},{confirm_cancel_all:'true'},{expected_updated_at:'2026'},{expected_updated_at:null},{reason_code:'other',reason_note:'no'}]){const h=harness();assert.equal((await h.api.POST(h.req(changes))).status,400);assert.equal(h.calls.length,0)}});
 await test('malformed or oversized cancellation body fails before RPC',async()=>{for(const raw of ['{', ' '.repeat(12001)]){const h=harness({raw});assert((await h.api.POST(h.req())).status>=400);assert.equal(h.calls.length,0)}});
 await test('stale, late and post-assignment rejection remains an error',async()=>{for(const error of ['AGRIMARKET_ORDER_CHANGED','AGRIMARKET_PRODUCER_CONFIRMATION_TIMEOUT','AGRIMARKET_RECOVERY_REQUIRED']){const h=harness({result:{ok:false,error}});const x=await h.api.POST(h.req());assert.equal(x.status,409);assert.equal(x.body.ok,false)}});
 await test('RPC failure is not success and does not leak internal provider errors',async()=>{const h=harness({dbError:true});const x=await h.api.POST(h.req());assert.equal(x.status,503);assert(!JSON.stringify(x).includes('SECRET'))});
 await test('idempotent cancellation reports original completion without claiming fresh stock changes',async()=>{const h=harness({result:{ok:true,already_done:true}});const x=await h.api.POST(h.req());assert.equal(x.status,200);assert.match(x.body.message,/already cancelled/);assert.match(x.body.message,/No stock/)});
 await test('review includes all item lines and never cancels without checklist confirmation',async()=>{const h=ui();h.find(n=>n.type==='button').props.onClick();h.render();assert(h.find(n=>n.props?.['aria-label']==='Cancel entire reservation'));const button=h.find(n=>n.type==='button'&&n.props.children==='Confirm cancellation of ALL items');assert.equal(button.props.disabled,true);assert.equal(h.calls.length,0);assert.equal(h.findAll(n=>n.type==='input'&&n.props.type==='checkbox').length,3);});
 await test('stale review is visibly blocked after order version changes',async()=>{const h=ui();h.find(n=>n.type==='button').props.onClick();h.render();h.change();h.render();assert(h.find(n=>n.props?.role==='alert'));assert(h.find(n=>n.type==='button'&&n.props.children==='Confirm cancellation of ALL items').props.disabled);assert.equal(h.calls.length,0)});
 await test('confirmed cancellation sends selected cuts only while explicitly cancelling whole reservation',async()=>{const h=ui();h.find(n=>n.type==='button').props.onClick();h.render();h.find(n=>n.type==='select').props.onChange({target:{value:'sold_outside_jride'}});h.render();h.findAll(n=>n.type==='input'&&n.props.type==='checkbox')[0].props.onChange({target:{checked:true}});h.render();h.findAll(n=>n.type==='input'&&n.props.type==='checkbox')[2].props.onChange({target:{checked:true}});h.render();const b=h.find(n=>n.type==='button'&&n.props.children==='Confirm cancellation of ALL items');assert.equal(b.props.disabled,false);b.props.onClick();b.props.onClick();await flush();assert.equal(h.calls.length,1);const payload=JSON.parse(h.calls[0].opt.body);assert.deepEqual(payload.affected_product_ids,[product]);assert.equal(payload.confirm_cancel_all,true);assert.equal(h.completed.length,1);});
 await test('two same-schedule cuts share cart group; different schedules and live animals do not',()=>{const c=load('lib/agrimarket/cartCompatibility.ts');const a={name:'Belly',cargo_class:'fresh_meat',availability_mode:'scheduled_harvest',harvest_start_at:'2026-09-25T21:00:00Z',harvest_end_at:'2026-09-25T22:00:00Z'};const b={...a,name:'Ribs'};assert.equal(c.cartConflict([a,b]),null);assert.equal(c.deliveryGroupKey(a),c.deliveryGroupKey(b));assert(c.cartConflict([a,{...b,harvest_start_at:'2026-09-26T21:00:00Z'}]));assert(c.cartConflict([a,{...b,cargo_class:'live_livestock'}]));});
 await test('vendor cut form preserves separate cut quantities/prices and unique names',()=>{const {normalizeButchering}=load('lib/agrimarket/butchering.ts');const body={species:'Pig',condition:'fresh',vehicle_requirement:'either',default_prep_minutes:15,is_active:true,butcher_start_at:'2027-01-02T05:00:00+08:00',butcher_end_at:'2027-01-02T06:00:00+08:00',order_cutoff_at:'2027-01-01T20:00:00+08:00',cuts:[{name:'Belly',price_per_kg:300,available_kg:8},{name:'Ribs',price_per_kg:250,available_kg:5}]};const p=normalizeButchering(body);assert.equal(p.cuts.length,2);assert.equal(p.cuts[0].price_per_kg,300);assert.equal(p.cuts[1].available_kg,5);assert.throws(()=>normalizeButchering({...body,cuts:[body.cuts[0],body.cuts[0]]}));});
 await test('SQL includes ownership/version/state/cash checks and atomic pause/release/audit',()=>{const file=fs.readdirSync(path.join(root,'supabase/migrations')).find(n=>n.endsWith('_agrimarket_reserved_cut_cancellation_v1.sql'));const s=read('supabase/migrations/'+file);for(const text of ['producer_id=p_producer_id FOR UPDATE','o.updated_at IS DISTINCT FROM p_expected_updated_at',"o.status NOT IN ('awaiting_producer','awaiting_harvest')",'customer_cash_collected_amount','assigned_driver_id IS NOT NULL','agrimarket_release_active_reservations_v1',"SET is_active=false",'producer_reservation_cancelled',"status='pending_customer'",'FROM PUBLIC,anon,authenticated'])assert(s.includes(text),text);assert(!/delete\s+from\s+public\.agrimarket_order_items/i.test(s));});
 await test('passenger web shows cancelled reservation reason instead of preparation/payment instructions',()=>{const f=load('lib/agrimarket/orderExpiry.ts').agrimarketExpiryNotice;const reason='Reserved cut no longer available - sold outside JRide. Affected cuts: Pig - Belly';const x=f({status:'cancelled',fulfillment_mode:'scheduled_harvest',cancel_reason:reason});assert.equal(x.title,'Reservation cancelled');assert.equal(x.message,reason);assert.equal(f({status:'awaiting_harvest',fulfillment_mode:'scheduled_harvest'}),null);assert.match(f({status:'cancelled',cancel_reason:'customer_reapproval_timeout',fulfillment_mode:'scheduled_harvest'}).title,/Approval time expired/);const page=read('app/agrimarket/order/page.tsx');assert(page.indexOf('{expiryNotice ? <>')<page.indexOf('Cash due now'));assert(page.includes('expiryNotice.message'));});
 console.log('Reservation cancellation/parts: '+passed+' groups passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
