CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN BYPASSRLS;
GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
CREATE TABLE public.passenger_addresses(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_addresses(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_addresses TO anon,authenticated,service_role;
CREATE TABLE public.passenger_device_session_events(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_device_session_events(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_device_session_events TO anon,authenticated,service_role;
CREATE TABLE public.passenger_device_sessions(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_device_sessions(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_device_sessions TO anon,authenticated,service_role;
CREATE TABLE public.passenger_free_ride_audit(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_free_ride_audit(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_free_ride_audit TO anon,authenticated,service_role;
CREATE TABLE public.passenger_profiles(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_profiles(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_profiles TO anon,authenticated,service_role;
CREATE TABLE public.passenger_promo_allowlist(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_promo_allowlist(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_promo_allowlist TO anon,authenticated,service_role;
CREATE TABLE public.passenger_promo_credits(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_promo_credits(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_promo_credits TO anon,authenticated,service_role;
CREATE TABLE public.passenger_promo_event_log(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_promo_event_log(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_promo_event_log TO anon,authenticated,service_role;
CREATE TABLE public.passenger_promo_redemptions(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_promo_redemptions(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_promo_redemptions TO anon,authenticated,service_role;
CREATE TABLE public.passenger_verifications(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_verifications(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_verifications TO anon,authenticated,service_role;
CREATE TABLE public.passenger_verification_requests(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.passenger_verification_requests(fixture) VALUES ('private fixture');
GRANT ALL ON public.passenger_verification_requests TO anon,authenticated,service_role;
CREATE TABLE public.password_reset_tokens(user_id uuid, passenger_id uuid, fixture text);
INSERT INTO public.password_reset_tokens(fixture) VALUES ('private fixture');
GRANT ALL ON public.password_reset_tokens TO anon,authenticated,service_role;
CREATE VIEW public.admin_free_ride_summary_v1 AS SELECT * FROM public.passenger_profiles;
GRANT SELECT ON public.admin_free_ride_summary_v1 TO anon,authenticated,service_role;
CREATE VIEW public.v_jride_android_first_ride_audit AS SELECT * FROM public.passenger_profiles;
GRANT SELECT ON public.v_jride_android_first_ride_audit TO anon,authenticated,service_role;
CREATE VIEW public.v_passenger_active_device_sessions AS SELECT * FROM public.passenger_profiles;
GRANT SELECT ON public.v_passenger_active_device_sessions TO anon,authenticated,service_role;
CREATE FUNCTION public.admin_approve_passenger(bigint,uuid) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.admin_reject_passenger(bigint,uuid,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.dispatcher_preapprove_passenger(bigint,uuid) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_passenger_claim_device_session(uuid,text,text,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_passenger_revoke_all_sessions(uuid,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_passenger_sign_out_device(uuid,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_passenger_validate_device_session(uuid,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_ensure_android_credit(uuid,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_expire_stale_reservations(text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_finalize_completed_booking(uuid,numeric,uuid,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_get_status(uuid,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_is_whitelisted(text,uuid,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_mark_message_seen(uuid,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_release_for_booking(uuid,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.jride_promo_reserve_for_booking(uuid,text,uuid,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.passenger_request_verification(uuid,text,text,text,text,text,text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
CREATE FUNCTION public.promo_try_use_free_ride(uuid,uuid,uuid) RETURNS void LANGUAGE plpgsql AS $$ BEGIN RETURN; END; $$;
