"use client";

import { useState } from "react";
import { eventConflicts, type Schedule } from "@/lib/operations-schedule";
import styles from "./schedule.module.css";

export default function EventsPanel({ state, admin, busy, today, act }: { state: Schedule; admin: boolean; busy: boolean; today: string; act: (action: string, extras: Record<string, unknown>) => Promise<unknown> }) {
  const [draft, setDraft] = useState({ title: "", category: "JRide event", audience: "Mixed audience", location: "", day: today < "2026-09-08" ? "2026-09-08" : today, start: "09:00", end: "10:00", participants: [] as string[], note: "" });
  const [cancelId, setCancelId] = useState("");
  const [reason, setReason] = useState("");
  const events = Object.values(state.plannedEvents || {}).sort((a,b) => a.day.localeCompare(b.day) || a.start.localeCompare(b.start));
  return <section className={styles.panel}><h2>Events and learning activities</h2><p>Plan JRide events, training and information drives for drivers, passengers or vendors. All times are Philippine time. Include travel and preparation in the reserved time.</p><p>Event assignments do not count as rest days. Existing duty owners stay responsible until coverage is arranged. If everyone attends during Core hours, stagger attendance or change the event time so Primary and Backup remain covered.</p>
    {admin && <details className={styles.taskForm}><summary>Plan an event</summary><form onSubmit={e => { e.preventDefault(); void act("create_event", draft); }}>
      <label htmlFor="event-title">Event title</label><input id="event-title" required maxLength={120} value={draft.title} onChange={e => setDraft({...draft,title:e.target.value})} />
      <label htmlFor="event-category">Activity type</label><select id="event-category" value={draft.category} onChange={e => setDraft({...draft,category:e.target.value})}>{["JRide event","Training / learning","Information drive"].map(t => <option key={t}>{t}</option>)}</select>
      <label htmlFor="event-audience">Audience</label><select id="event-audience" value={draft.audience} onChange={e => setDraft({...draft,audience:e.target.value})}>{["Drivers","Passengers","Vendors","Staff","Mixed audience"].map(t => <option key={t}>{t}</option>)}</select>
      <label htmlFor="event-location">Location / meeting link</label><input id="event-location" required maxLength={200} value={draft.location} onChange={e => setDraft({...draft,location:e.target.value})} />
      <div className={styles.actions}><div><label htmlFor="event-day">Date in an open planning month</label><input id="event-day" type="date" required min={today < "2026-09-08" ? "2026-09-08" : today} value={draft.day} onChange={e => setDraft({...draft,day:e.target.value})} /></div><div><label htmlFor="event-start">Start</label><input id="event-start" type="time" required value={draft.start} onChange={e => setDraft({...draft,start:e.target.value})} /></div><div><label htmlFor="event-end">End</label><input id="event-end" type="time" required value={draft.end} onChange={e => setDraft({...draft,end:e.target.value})} /></div></div>
      <fieldset><legend>Coordinators attending</legend>{state.employees.map(p => <label key={p.id} style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" style={{width:"auto",minHeight:"auto"}} checked={draft.participants.includes(p.id)} onChange={e => setDraft({...draft,participants:e.target.checked ? [...draft.participants,p.id] : draft.participants.filter(id => id !== p.id)})} />{p.name}</label>)}</fieldset>
      <label htmlFor="event-note">Instructions / preparation</label><textarea id="event-note" maxLength={500} rows={3} value={draft.note} onChange={e => setDraft({...draft,note:e.target.value})} />
      <p>Saving shows any conflicts for Admin to resolve; it does not release existing duties or rest days.</p><button className={styles.primary} disabled={busy || !draft.participants.length}>Save event</button>
    </form></details>}
    {!events.length && <p>No events planned yet.</p>}
    {events.map(e => { const conflicts = eventConflicts(state,e); return <article className={styles.task} key={e.id}><div className={styles.editorTitle}><h3>{e.title}</h3><span className={styles.badge}>{e.status === "cancelled" ? "Cancelled" : e.day < today ? "Past event" : "Planned"}</span></div><p>{e.day} / {e.start} - {e.end} PHT / {e.location}</p><p>{e.category} / {e.audience}</p><p>Attending: {e.participants.map(id => state.employees.find(p => p.id === id)?.name || id).join(", ")}</p>{e.note && <p className={styles.instructions}>{e.note}</p>}{!!conflicts.length && <div className={styles.warning}><strong>Schedule conflicts - resolve before finalizing</strong><ul>{conflicts.map(c => <li key={c}>{c}</li>)}</ul></div>}{admin && e.status === "planned" && e.day >= today && (cancelId === e.id ? <form onSubmit={ev => {ev.preventDefault(); void act("cancel_event",{eventId:e.id,note:reason});}}><label htmlFor="event-cancel-reason">Cancellation reason</label><input id="event-cancel-reason" required maxLength={500} value={reason} onChange={ev => setReason(ev.target.value)} /><button disabled={busy || !reason.trim()}>Confirm cancellation</button><button type="button" onClick={() => setCancelId("")}>Keep event</button></form> : <button disabled={busy} onClick={() => {setCancelId(e.id);setReason("");}}>Cancel event</button>)}</article>; })}
  </section>;
}
