begin;

alter table public.vendor_accounts
  add column if not exists performance_metrics_started_at timestamptz;

update public.vendor_accounts
set performance_metrics_started_at = now()
where performance_metrics_started_at is null;

alter table public.vendor_accounts
  alter column performance_metrics_started_at set default now();

alter table public.vendor_accounts
  alter column performance_metrics_started_at set not null;

create table if not exists public.analytics_test_accounts (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null check (subject_type in ('passenger_user', 'vendor', 'driver')),
  subject_id uuid not null,
  reason text not null,
  active boolean not null default true,
  marked_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject_type, subject_id)
);

create index if not exists analytics_test_accounts_active_idx
  on public.analytics_test_accounts (subject_type, active, subject_id);

create table if not exists public.analytics_booking_exclusions (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  reason text not null,
  active boolean not null default true,
  marked_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (booking_id)
);

create index if not exists analytics_booking_exclusions_active_idx
  on public.analytics_booking_exclusions (active, booking_id);

create table if not exists public.vendor_presence_minutes (
  vendor_id uuid not null references public.vendor_accounts(id) on delete cascade,
  minute_started_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  accepting_orders boolean not null,
  client text not null default 'web',
  created_at timestamptz not null default now(),
  primary key (vendor_id, minute_started_at)
);

create index if not exists vendor_presence_minutes_seen_idx
  on public.vendor_presence_minutes (vendor_id, last_seen_at desc);

create table if not exists public.vendor_availability_events (
  id bigint generated by default as identity primary key,
  vendor_id uuid not null references public.vendor_accounts(id) on delete cascade,
  accepting_orders boolean not null,
  changed_at timestamptz not null default now(),
  source text not null default 'vendor_profile'
);

create index if not exists vendor_availability_events_vendor_time_idx
  on public.vendor_availability_events (vendor_id, changed_at desc);

create or replace function public.record_vendor_availability_event_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.accepting_orders is distinct from old.accepting_orders then
    insert into public.vendor_availability_events (
      vendor_id,
      accepting_orders,
      changed_at,
      source
    ) values (
      new.id,
      new.accepting_orders,
      now(),
      'vendor_accounts_trigger'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists vendor_accounts_availability_event_v1 on public.vendor_accounts;
create trigger vendor_accounts_availability_event_v1
after insert or update of accepting_orders on public.vendor_accounts
for each row execute function public.record_vendor_availability_event_v1();

insert into public.vendor_availability_events (
  vendor_id,
  accepting_orders,
  changed_at,
  source
)
select
  vendor.id,
  vendor.accepting_orders,
  vendor.performance_metrics_started_at,
  'metrics_baseline'
from public.vendor_accounts vendor
where not exists (
  select 1
  from public.vendor_availability_events event
  where event.vendor_id = vendor.id
);

create or replace function public.capture_takeout_vendor_response_times_v1()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_status text := lower(trim(coalesce(old.vendor_status, '')));
  new_status text := lower(trim(coalesce(new.vendor_status, '')));
  response_reason text := lower(trim(coalesce(new.vendor_cancel_reason, new.cancel_reason, '')));
  response_time timestamptz := now();
begin
  if lower(trim(coalesce(new.service_type, ''))) <> 'takeout' then
    return new;
  end if;

  if (
    new_status = 'vendor_timeout'
    or response_reason like '%did not respond within%'
    or response_reason like '%vendor timeout%'
  ) then
    new.vendor_timeout_at := coalesce(new.vendor_timeout_at, response_time);
    new.vendor_responded_at := coalesce(new.vendor_responded_at, new.vendor_timeout_at, response_time);
    return new;
  end if;

  if old_status in ('', 'requested', 'vendor_pending')
     and new_status in ('cancelled', 'canceled') then
    new.vendor_rejected_at := coalesce(new.vendor_rejected_at, response_time);
    new.vendor_responded_at := coalesce(new.vendor_responded_at, new.vendor_rejected_at, response_time);
    return new;
  end if;

  if new_status in (
    'vendor_accepted',
    'accepted',
    'driver_assigned',
    'driver_accepted',
    'preparing',
    'pickup_ready',
    'rider_arrived_vendor',
    'arrived_vendor',
    'picked_up',
    'delivering',
    'completed'
  ) then
    new.vendor_accepted_at := coalesce(new.vendor_accepted_at, response_time);
    new.vendor_responded_at := coalesce(new.vendor_responded_at, new.vendor_accepted_at, response_time);
  end if;

  return new;
end;
$$;

drop trigger if exists bookings_takeout_vendor_response_times_v1 on public.bookings;
create trigger bookings_takeout_vendor_response_times_v1
before update of vendor_status, vendor_cancel_reason, cancel_reason on public.bookings
for each row execute function public.capture_takeout_vendor_response_times_v1();

insert into public.analytics_test_accounts (
  subject_type,
  subject_id,
  reason,
  active,
  marked_by
)
select
  'passenger_user',
  profile.user_id,
  'Known JRide test or dummy passenger account',
  true,
  'migration:vendor_performance_baseline_v1'
from public.passenger_profiles profile
where lower(trim(coalesce(profile.email, ''))) in (
    'test@lamut.com',
    'test@gmail.com',
    'jride.test.review@gmail.com',
    'test-login@drivers.jride.local'
  )
   or lower(trim(coalesce(profile.full_name, ''))) in (
    'test book lamut',
    'jride test',
    'lamut tester',
    'test user'
  )
on conflict (subject_type, subject_id)
do update set
  reason = excluded.reason,
  active = true,
  marked_by = excluded.marked_by,
  updated_at = now();

alter table public.analytics_test_accounts enable row level security;
alter table public.analytics_booking_exclusions enable row level security;
alter table public.vendor_presence_minutes enable row level security;
alter table public.vendor_availability_events enable row level security;

comment on column public.vendor_accounts.performance_metrics_started_at is
  'Public vendor performance metrics include only activity at or after this timestamp.';

comment on table public.analytics_test_accounts is
  'Explicit account exclusions for analytics. Never infer test status from partial name matching.';

comment on table public.analytics_booking_exclusions is
  'Explicit per-booking analytics exclusions. Operational records remain intact.';

comment on table public.vendor_presence_minutes is
  'One server-recorded presence row per vendor per minute while the vendor portal is active.';

comment on table public.vendor_availability_events is
  'Append-only vendor open or closed state changes used for behavior reporting.';

commit;
